---
params:
  sample_id: "TO_BE_SET"
  segmentation_id: "TO_BE_SET"
  normalisation_id: "TO_BE_SET"
  xe_raw_path: "TO_BE_SET"
  xe_path: "TO_BE_SET"
  default_assay: "TO_BE_SET"

title: "Report: Standard Seurat analysis for sample `r params$sample_id` segmented by `r params$segmentation_id` and normalised by `r params$normalisation_id`"
author: "Mariia Bilous"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(Seurat)
library(ggplot2)
library(dplyr)
```

# Load raw and QC seurat objects

```{r}
xe_raw <- readRDS(params$xe_raw_path)
xe     <- readRDS(params$xe_path)
```

Get QC parameters

```{r}
qc_params <- xe@misc$QC_metadata
```

Mark filtered cells and genes

```{r}
xe_raw@meta.data <- xe_raw@meta.data %>%
  mutate(is_QC = rownames(.) %in% colnames(xe))
```

Get cell/gene filtering

```{r}
# Cells
removed_cells <- ncol(xe_raw) - ncol(xe)
total_cells <- ncol(xe_raw)
percentage_removed_cells <- 100 * removed_cells / total_cells

msg_cells <- sprintf("N = %d cells out of %d were removed (i.e., %.2f%%)",
                     as.integer(removed_cells),
                     as.integer(total_cells),
                     percentage_removed_cells)

# Genes
removed_genes <- nrow(xe_raw) - nrow(xe)
total_genes <- nrow(xe_raw)
percentage_removed_genes <- 100 * removed_genes / total_genes

msg_genes <- sprintf("N = %d genes out of %d were removed (i.e., %.2f%%)",
                     as.integer(removed_genes),
                     as.integer(total_genes),
                     percentage_removed_genes)
```

# Generate QC plots

```{r, fig.height=7}
fields_to_plot <- c("nCount", "nFeature")
fields_to_plot_names <- paste0(fields_to_plot, paste0("_", params$default_assay))

p_qc_cells <- xe_raw@meta.data %>%
  ggplot(aes_string(x = fields_to_plot_names[1], y = fields_to_plot_names[2], color = "is_QC")) +
  geom_point() +
  scale_color_manual(values = c("gray","black")) +
  geom_vline(xintercept = c(qc_params$min_counts, qc_params$max_counts), col = "darkred") +
  geom_hline(yintercept = c(qc_params$min_features, qc_params$max_features), col = "darkred") +
  ggtitle(msg_cells) +
  theme_classic() +
  theme(aspect.ratio = 1)


gene_df <- data.frame(
  gene_detection = rowSums(GetAssayData(xe_raw, assay = "Xenium", layer = "counts")>0),
  gene_mean_counts = rowMeans(GetAssayData(xe_raw, assay = "Xenium", layer = "counts")),
  is_QC = rownames(xe_raw) %in% row.names(xe)
)
p_qc_genes <- gene_df %>% ggplot(aes_string(x = colnames(gene_df)[1], y = colnames(gene_df)[2]), color = is_QC) +
  geom_point() +
  scale_color_manual(values = c("gray","black")) +
  geom_vline(xintercept = qc_params$min_cells, col = "darkred") +
  ggtitle(msg_genes) +
  theme_classic() +
  theme(aspect.ratio = 1)

plot(p_qc_cells + p_qc_genes)
```

# Dimred and clustering

## nPCs

```{r, fig.height=3}
st_analysis_params <- xe@misc$standard_seurat_analysis_meta
ElbowPlot(xe, ndims = st_analysis_params$n_dims) + geom_vline(xintercept = st_analysis_params$n_dims)
```

## UMAP and clustering

```{r, fig.height=8}
UMAPPlot(xe, group.by = "clusters", label = T, repel = T) & theme_void() & theme(aspect.ratio = 1)
DimPlot(xe, reduction = "spatial", group.by = "clusters") & theme_void() & coord_fixed()
```
